-- =====================================================================
-- ACTIVIDAD GRUPO 8 - ARTIFICIAL INTELLIGENCE
-- Supabase Leaderboard Database Schema
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- =====================================================================

-- 1. Create the leaderboard table
CREATE TABLE IF NOT EXISTS public.leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  time_sec INTEGER NOT NULL,
  penalties INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow anyone (anon) to read the leaderboard
CREATE POLICY "Allow public read" 
ON public.leaderboard 
FOR SELECT 
TO anon, authenticated
USING (true);

-- 4. Policy: Allow anyone (anon) to insert their score
CREATE POLICY "Allow public insert" 
ON public.leaderboard 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- 5. Optional initial benchmark scores (seed data)
INSERT INTO public.leaderboard (name, time_sec, penalties)
VALUES 
  ('Ada_Lovelace', 104, 0),
  ('Alan_Turing', 135, 0),
  ('Claude_Shannon', 168, 0),
  ('Grace_Hopper', 195, 0),
  ('John_McCarthy', 220, 0),
  ('Marvin_Minsky', 245, 0),
  ('Geoffrey_Hinton', 270, 0),
  ('Yann_LeCun', 300, 0),
  ('Demis_Hassabis', 330, 0),
  ('Fei_Fei_Li', 360, 0)
ON CONFLICT DO NOTHING;
